name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ../src -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE -- -j2

  build-msvc:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake ../src -DCMAKE_BUILD_TYPE=%BUILD_TYPE%

    - name: Build
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config %BUILD_TYPE%
